---
- name: Ensure `ignore_errors: yes` is set in `0080-system-configurations.yml`
  lineinfile:
    path: ~/kubespray/roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
    insertafter: "setenforce 0"
    line: "  ignore_errors: yes"
  when: "'setenforce 0' in lookup('file', '~/kubespray/roles/kubernetes/preinstall/tasks/0080-system-configurations.yml')"

- name: Ensure `ignore_errors: yes` is set in `SELINUX=disabled` task
  lineinfile:
    path: ~/kubespray/roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
    insertafter: "line: SELINUX=disabled"
    line: "  ignore_errors: yes"
  when: "'line: SELINUX=disabled' in lookup('file', '~/kubespray/roles/kubernetes/preinstall/tasks/0080-system-configurations.yml')"

- name: Clone Kubespray Repository
  git:
    repo: "https://github.com/kubernetes-sigs/kubespray"
    dest: "~/kubespray"
    version: "release-2.23"

- name: Setup Python Virtual Environment
  shell: |
    python3 -m venv ~/venv
    source ~/venv/bin/activate
    pip install -U pip ruamel_yaml selinux

- name: Copy inventory
  shell: |
    cp -rfp inventory/sample inventory/mycluster
    declare -a IPS=({{ k8s_master_ip }} {{ k8s_worker_ips | join(' ') }})
    CONFIG_FILE=inventory/mycluster/hosts.yaml python3 contrib/inventory_builder/inventory.py ${IPS[@]}

- name: Deploy Kubernetes Cluster with Kubespray
  shell: |
    ansible-playbook -i inventory/mycluster/hosts.yaml --become --become-user=root cluster.yml 