---
- name: Install BIND packages
  yum:
    name:
      - bind
      - bind-utils
    state: present

- name: Create DNS zone directory
  file:
    path: /var/named
    state: directory
    owner: named
    group: named
    mode: '0755'

- name: Deploy DNS zone file
  template:
    src: project.com.zone.j2
    dest: /var/named/{{ domain }}.zone
    owner: named
    group: named
    mode: '0644'
  notify: restart named

- name: Configure named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'
  notify: restart named

- name: Configure firewall
  firewalld:
    service: dns
    permanent: yes
    state: enabled
  notify: restart firewalld

- name: Start and enable named service
  systemd:
    name: named
    state: started
    enabled: yes 