---
- name: restart postfix
  systemd:
    name: postfix
    state: restarted

- name: restart dovecot
  systemd:
    name: dovecot
    state: restarted

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted 